export const SIGNIN_REQUEST = "auth/LOGIN_REQUEST";
export const SIGNIN_SUCCESS = "auth/LOGIN_SUCCESS";
export const SIGNIN_FAILURE = "auth/LOGIN_FAILURE";

export const LOGOUT_REQUEST = "auth/LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "auth/LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "auth/LOGOUT_FAILURE";

export const RECIEVE_AUTH_REQUEST = "auth/RECIEVE_AUTH_REQUEST";
export const RECIEVE_AUTH_SUCCESS = "auth/RECIEVE_AUTH_SUCCESS";
export const RECIEVE_AUTH_FAILURE = "auth/RECIEVE_AUTH_FAILURE";
