export const SIGNIN_REQUEST = "auth/LOGIN_REQUEST";
export const SIGNIN_SUCCESS = "auth/LOGIN_SUCCESS";
export const SIGNIN_FAILURE = "auth/LOGIN_FAILURE";

export const RECIEVE_AUTH_REQUEST = "auth/RECIEVE_AUTH_REQUEST";
export const RECIEVE_AUTH_SUCCESS = "auth/RECIEVE_AUTH_SUCCESS";
export const RECIEVE_AUTH_FAILURE = "auth/RECIEVE_AUTH_FAILURE";

export const LOGOUT_SUCCESS = "auth/LOGOUT_SUCCESS";

export const SHOW_LOADING = "auth/SHOW_LOADING";
export const HIDE_LOADING = "auth/HIDE_LOADING";
